### ISSUE TITLE
no dataset

### ISSUE THREAD

**Issue by LuHgggG** [AEGISEDGE/NPTM#1]
not find corpus-by-user.bin

**Comment by LuHgggG** [comment]
can u provide a runnable dataset? thank you

**Comment by AEGISEDGE** [comment]
The corpus data is too large to be uploaded. So I provide a zip file containing binary version of twitter-political-archive. u can check the `Data and model preparation` section in `README.md` before running. To use this zip file, just upzip it and place the `corpus_obj.bin` at the same directory with `run.py`. Then, move `vocab.bin` file to `data/twitter2016` directory.

**Comment by LuHgggG** [comment]
can u provide a correct data form, when i run     if os.path.exists("corpus_obj.bin") and not args.disablerapidload:
        corpus = pickle.load(open("corpus_obj.bin", 'rb'))
        corpus_name = corpus["name"] , it comes with typeError:TypeError:
list indices must be integers or slices, not str

**Comment by AEGISEDGE** [comment]
Sorry I forgot check the working directory dependency. I have correct the "data" directory and some directory setting in "run.py". The processed version of Twitter-political-archive has uploaded at "data/corpus/twitter2016/twitter2016.zip". u can unzip it directly to get binary version of data.

**Comment by LuHgggG** [comment]
thank u
